loader_mode: P3MP
gpu: '0'
backbone: mobilenetv2_human #mobilenetv2_human
data_set: P3M
save_file: 4
img_size: 512
batch_size: 2
num_worker: 8
pretrain_path: ''
lr: 0.0005
weight: 0.0005
port: 23549
epoch: 100
aug_mixup: false
aug_shadow: true
aug_crop: false
val_per_epoch: 1
show_per_epoch: 150
save_per_epoch: 5
in_channels: 4
hr_channels: 32
warmup_step: 5
amp: true
fusion: false

rssn_denoise: false
bgPath_denoise: ''
fgPath_denoise: ''
crop_size: 512
val_size: 1600

im_path: F:/matting/AIM-500/original/
fg_path: ''
bg_path: ''
gt_path: F:/matting/AIM-500/mask/
val_img_path: F:/matting/AIM-500/original/ # blurred_image/  original_image/
val_gt_path: F:/matting/AIM-500/mask/
trimap_path: ''
show_img_path: F:/matting/AIM-500/original/
show_gt_path: F:/matting/AIM-500/mask/
