loader_mode: P3MP
use_user_map: false
fusion: false
inter_num: 1
gpu: '2,3'
backbone: mobilenetv2 #mobilenetv2_human
data_set: P3M
save_file: 2
img_size: 512
crop_size: 512
batch_size: 8
num_worker: 8
pretrain_path: ''
lr: 0.0005
weight: 0.0005
port: 23550
epoch: 100
aug_mixup: false
aug_shadow: true
aug_crop: false
val_per_epoch: 1
show_per_epoch: 150
save_per_epoch: 5
in_channels: 3
hr_channels: 32
warmup_step: 5
amp: true

rssn_denoise: false
bgPath_denoise: ''
fgPath_denoise: ''

val_size: 1600

im_path: /data/P3M-10k/train/blurred_image/
fg_path: ''
bg_path: ''
gt_path: /data/P3M-10k/train/mask/
val_img_path: /data/P3M-10k/validation/P3M-500-P/blurred_image/
val_gt_path: /data/P3M-10k/validation/P3M-500-P/mask/
trimap_path: ''
show_img_path: /data/P3M-10k/validation/P3M-500-P/blurred_image/
show_gt_path: /data/P3M-10k/validation/P3M-500-P/mask/
