CUDNN:
  BENCHMARK: true
  DETERMINISTIC: false
  ENABLED: true
GPUS: (0,1,2,3)
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 6
PRINT_FREQ: 100

DATASET:
  DATASET: person
  ROOT: '/data1/wjw/work/segSet/portrait_Seg/'
  TEST_SET: 'list/person/val_true.txt'
  TRAIN_SET: 'list/person/train_labels.txt'
  NUM_CLASSES: 2
MODEL:
  NAME: seg_hrnet_ocr
  PRETRAINED: 'pretrained_models/HRNet_W48_C_ssld_pretrained.pth'
  EXTRA:
    FINAL_CONV_KERNEL: 1
    STAGE1:
      NUM_MODULES: 1
      NUM_RANCHES: 1
      BLOCK: BOTTLENECK
      NUM_BLOCKS:
      - 4
      NUM_CHANNELS:
      - 64
      FUSE_METHOD: SUM
    STAGE2:
      NUM_MODULES: 1
      NUM_BRANCHES: 2
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      FUSE_METHOD: SUM
    STAGE3:
      NUM_MODULES: 4
      NUM_BRANCHES: 3
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      FUSE_METHOD: SUM
    STAGE4:
      NUM_MODULES: 3
      NUM_BRANCHES: 4
      BLOCK: BASIC
      NUM_BLOCKS:
      - 4
      - 4
      - 4
      - 4
      NUM_CHANNELS:
      - 48
      - 96
      - 192
      - 384
      FUSE_METHOD: SUM
LOSS:
  USE_OHEM: false
  OHEMTHRES: 0.9
  OHEMKEEP: 131072
TRAIN:
  IMAGE_SIZE:
  - 640
  - 640
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 8
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 10
  RESUME: true
  OPTIMIZER: sgd
  LR: 0.01
  WD: 0.0005
  MOMENTUM: 0.9
  NESTEROV: false
  FLIP: true
  MULTI_SCALE: true
  DOWNSAMPLERATE: 1
  IGNORE_LABEL: 255
  SCALE_FACTOR: 11
TEST:
  IMAGE_SIZE:
  - 640
  - 640
  BASE_SIZE: 640
  BATCH_SIZE_PER_GPU: 4
#  NUM_SAMPLES: 2000
  FLIP_TEST: false
  MULTI_SCALE: false
